name: 04 - Using Actions

on: 
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 0.set default directory
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      # 1.Checkout the code from the repository so runners can access it
      - name: Checkout Code
        uses: actions/checkout@v4
      # print working folders for debug
      - name: Printing Folders
        run: ls
      # set up node to specific version
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # 2.Install deps of our react application will fail cause not set working directory yet
      - name: Install Dependencies
        run: npm ci  
      # 3.Execute automated tests
      - name: Run Unit Tests
        run: npm run test
      
      ### primary flows ###
      # 1.Checkout the code from the repository so runners can access it
      # 2.Install deps of our react application will fail cause not set working directory yet
      # 3.Execute automated tests

      
