
name: 17 - 3 - Custom Actions - Docker


on:
  workflow_dispatch:
    inputs:
      url:
        description: URL to ping
        type: choice
        options:
          - 'https://www.google.com'
          - 'aaaaswww.google.com'
          - 'https://www.invalid-but-url-format.com'
      max_trials: 
        description: max_trials to ping
        default: '10'
        required: false
      delay:
        description: time between ping
        default: '5'
        required: false

  

permissions:
  contents: write
  pull-requests: write

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: update-deps
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}