
name: 17 - 3 - Custom Actions - Docker


on:
  workflow_dispatch:
    inputs:
      url:
        description: URL to ping
        type: string
        default: 'https://www.google.com'
  

permissions:
  contents: write
  pull-requests: write

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        id: update-deps
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}